# ===========================================================================
# Example EasyPanel Template
# ===========================================================================
#
# Purpose:
# --------
#
# This file is an example EasyPanel configuration for self hosting
# Maybe on your local machine or on a cloud VPS.
#
# The configuration below is a "standard" setup, but may require modification
# for your specific environment.
#
# Setup:
# ------
#
# To run this, you should read the setup guide:
#
# https://github.com/maybe-finance/maybe/blob/main/docs/hosting/docker.md
#
# Troubleshooting:
# ----------------
#
# If you run into problems, you should open a Discussion here:
#
# https://github.com/maybe-finance/maybe/discussions/categories/general
#

services:
  - name: app
    image: ghcr.io/maybe-finance/maybe:latest
    volumes:
      - name: app-storage
        path: /rails/storage
    ports:
      - host: 3000
        container: 3000
    restart_policy: unless-stopped
    environment:
      - name: SELF_HOSTING_ENABLED
        value: "true"
      - name: RAILS_FORCE_SSL
        value: "false"
      - name: RAILS_ASSUME_SSL
        value: "false"
      - name: GOOD_JOB_EXECUTION_MODE
        value: async
      - name: SECRET_KEY_BASE
        value: ${SECRET_KEY_BASE:?}
      - name: DB_HOST
        value: postgres
      - name: POSTGRES_DB
        value: ${POSTGRES_DB:-maybe_production}
      - name: POSTGRES_USER
        value: ${POSTGRES_USER:-maybe_user}
      - name: POSTGRES_PASSWORD
        value: ${POSTGRES_PASSWORD:?}
    depends_on:
      - name: postgres
        condition: service_healthy

  - name: postgres
    image: postgres:16
    restart_policy: unless-stopped
    volumes:
      - name: postgres-data
        path: /var/lib/postgresql/data
    environment:
      - name: POSTGRES_USER
        value: ${POSTGRES_USER:-maybe_user}
      - name: POSTGRES_DB
        value: ${POSTGRES_DB:-maybe_production}
      - name: POSTGRES_PASSWORD
        value: ${POSTGRES_PASSWORD:?}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  - name: app-storage
  - name: postgres-data
